// This file is part of libbeauty project.
// It is subject to the license terms in the LICENSE file found in the top-level directory

#ifndef LIBBEAUTY_VERSION_HPP
#define LIBBEAUTY_VERSION_HPP

#define LIBBEAUTY_VERSION_MAJOR    1
#define LIBBEAUTY_VERSION_MINOR    0
#define LIBBEAUTY_VERSION_REVISION 1
#define LIBBEAUTY_VERSION_STATUS   ""

#define LIBBEAUTYAUX_STR_EXP(__A)  #__A
#define LIBBEAUTYAUX_STR(__A)      LIBBEAUTYAUX_STR_EXP(__A)

#define LIBBEAUTYAUX_STRW_EXP(__A)  L ## #__A
#define LIBBEAUTYAUX_STRW(__A)      LIBBEAUTYAUX_STRW_EXP(__A)

#define LIBBEAUTY_VERSION          LIBBEAUTYAUX_STR(LIBBEAUTY_VERSION_MAJOR) "." LIBBEAUTYAUX_STR(LIBBEAUTY_VERSION_MINOR) "." LIBBEAUTYAUX_STR(LIBBEAUTY_VERSION_REVISION) LIBBEAUTY_VERSION_STATUS

/* old  style version constants*/
#define LIBBEAUTY_MAJOR_VERSION    LIBBEAUTY_VERSION_MAJOR
#define LIBBEAUTY_MINOR_VERSION    LIBBEAUTY_VERSION_MINOR
#define LIBBEAUTY_SUBMINOR_VERSION LIBBEAUTY_VERSION_REVISION

#endif // LIBBEAUTY_VERSION_HPP
